version: '{build}'
build_script:
- ps: ./Build.ps1 
test: off
artifacts:
- path: artifacts/SerilogMetrics*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: xoBgXlnyTeh+PMTdVWf6WkqJBwMSTx/5k9gikwuv15S/fiJjlPBfpU4eblJvGMoq
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: JFjWbeRdJJLejLniefdDDDBMtVewsY3hBgXL5sZsIzL9xnymXVkOoeqFEEAfM/LGrQI5hfJLZ5jjXxDCnnpvkZpJzDqdTLPzHq2h76VqTiU=
  force_update: true
  artifact: /SerilogMetrics*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master